### PR TITLE
improve: post name

### PR DESCRIPTION
**Pull request by myviridis**

### CODE REVIEW

**Comment by zaiste** [comment]
@myviridis please, make it also lowercase

**Comment by tomkuk** [comment]
@myviridis there is also missing underscore between meet and nukomeeter

**Comment by myviridis** [comment]
OK. I've changed it. But note, that other post titles are also in uppercase eg. La Gueleton, NodeJS etc.

**Comment by myviridis** [comment]
added

*Kasia Popek*

Communications Manager at Nukomeet


___


You can contact me at

mail *kasia@nukomeet.com*

mobile *+48 609 160 095*


Visit our website *www.nukomeet.com*




On Fri, Jul 10, 2015, at 12:22 PM, Tomek Kuklis wrote:
> @myviridis[1] there is also missing underscore between meet and
> nukomeeter


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/myviridis
  2. https://github.com/nukomeet/nukomeet.com/pull/194#issuecomment-120357125

**Comment by tomkuk** [comment]
@myviridis yes I notice it, but lets try standardise it somehow so we always have underscore instead of spaces and all text lowercase

**Comment by myviridis** [comment]
OK. I just explain that I could not know this in comparison to the
previous posts

*Kasia Popek*

Communications Manager at Nukomeet


___


You can contact me at

mail *kasia@nukomeet.com*

mobile *+48 609 160 095*


Visit our website *www.nukomeet.com*




On Fri, Jul 10, 2015, at 01:44 PM, Tomek Kuklis wrote:
> @myviridis[1] yes I notice it, but lets try standardise it somehow so
> we always have underscore instead of spaces and all text lowercase


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/myviridis
  2. https://github.com/nukomeet/nukomeet.com/pull/194#issuecomment-120393022

**Pull request merged**
